package pe.LaCasona.backend_casona.models.DTO;

public enum Producto {
    SIMPLE_DE_POLLO, CHESSE, ROYAL, ESPECIAL, MIXTA, CASONA, CHORIPAN,
    CAFE, INFUSIONES, CHICHA_MORADA, JARRA_CHICHA_MORADA, INKA_COLA, COCA_COLA, GUARANA, AGUA_MINERAL,
    CHORIZO, HOTDOG, JAMON, QUESO, HUEVO,
    SALCHIPAPA, SALCHIPOLLO
}
